### ISSUE TITLE
qt5.11.2-vc14-64 missing dependecies

### ISSUE THREAD

**Issue by artemishenkov** [Open-Cascade-SAS/OCCT-samples-csharp#2]
Hello, I have converted the C# Sample project to Visual Studio 2019. When I run the project I get this error:
System.IO.FileNotFoundException: 'Could not load file or assembly 'OCCTProxy.dll' or one of its dependencies. The specified module could not be found.'
Then I've copied all third party libraries to one folder but when I run checkDLL64 I get such errors:
1) "Qt5Guid.dll" Loading... FAILED!
  Error #126: The specified module could not be found!
    libGLESv2d.dll not found!
2) "Qt5Quickd.dll" Loading... FAILED!
  Error #126: The specified module could not be found!
      libGLESv2d.dll not found!
3) "Qt5Widgetsd.dll" Loading... FAILED!
  Error #126: The specified module could not be found!
      libGLESv2d.dll not found!
P.S. Sorry for posting this question here, but I got an error when I tried to publish it on https://dev.opencascade.org/forums

**Comment by gkv311** [comment]
> P.S. Sorry for posting this question here, but I got an error when I tried to publish it on

Please use contact form to report authorization issues (I hope the form works ;)):
https://dev.opencascade.org/webform/contact_us

> checkDLL64 I get such errors:

I don't think that OCCTProxy.dll depends on any Qt libraries - these are probably comes from TKTInspector, which is not used / should not be used by C# sample. So that all Qt5Guid.dll/Qt5Quickd.dll could be removed altogether.

Maybe checkDLL64 reports more errors on some other libraries, that actually used?

**Comment by artemishenkov** [comment]
Thanks for the help, appreciate it!
