### ISSUE TITLE
c# wrapper using Pinvoke

### ISSUE THREAD

**Issue by bhupiister** [Open-Cascade-SAS/OCCT-samples-csharp#3]
Is there a C# wrapper based on Pinvoke? I need to use this plugin inside unity.
Any help will be appreciated.

**Comment by gkv311** [comment]
Why Pinvoke? What is the problem in using C++/CLI wrapper with Unity? Does it unable to load C# DLL?

**Comment by bhupiister** [comment]
@gkv311  Managed c++ dlls does not work in Unity
https://forum.unity.com/threads/is-c-cli-forbidden-in-unity.700115/
https://stackoverflow.com/questions/5313351/c-cli-wrapper-for-native-c-c-code-unable-to-load-in-unity3d

I have gone through above two links which is why I want Pinvoke method.

**Comment by gkv311** [comment]
@bhupiister, thanks for the links clarifying why this wouldn't work - it is because Unity abuses .NET ecosystem and converts all managed code provided as DLLs instead of just loading them:
> So yes, (for now) ANY not JIT-compile language is forbidden at ANY depth of (externally visible) dependency, since neither Mono nor IL2CPP can handle transitions between the two compilation paradigms.

>C++/CLI assemblies are not working with Unity, as Unity is relying on Mono that doesn't support mixed assemblies. The only workaround is to call functions from a dll with classic p/invoke

As for original question, C++/CLI is a powerful language allowing to write a complex code intermixing managed and unmanaged parts. In contrast, Pinvoke is a very low-level interface allowing to call C-alike functions exported from DLLs.

It is impractical writing such wrapper over C++ by hand - without utilizing automated code generators like SWIG. Open Cascade provides a [commercial sample](https://dev.opencascade.org/project/occ-c-wrapper) of such C# wrapper over OCCT framework, which in my understanding should be compatible with Unity as it indeed relies on Pinvoke.

**Comment by bhupiister** [comment]
@gkv311 Thanks for your reply. Any idea about it's license and cost? Though, I was looking for open source solution, if available.

**Comment by gkv311** [comment]
@bhupiister 
It is better [contacting Open Cascade](https://dev.opencascade.org/webform/contact_us) for prices and conditions.

Just curious, how is that you are looking for an open source solution for such a proprietary thing as Unity (in my understanding)? Why not also using something open instead of Unity?

**Comment by bhupiister** [comment]
@gkv311 because at the moment, I am first trying to build a software that can actually generate some profit for the company, and unity allows that until you reach their limit of $100,000 in revenue. I don't mind paying unity the licence fees once I make money. So I was hoping if OpenCascade has some arrangements of that kind.

**Comment by gkv311** [comment]
@bhupiister, thanks for clarification.

I guess that such conditions might look tempting for Startups, though I always fill worried on a vendor-lock due to premature choice of an engine at earlier stages just because it is "free" before you become big and healthy, as it is usually very difficult and expensive to switch later on. Like struggles of development team of System Shock remake: https://youtu.be/pE97vZLC_fA?t=402

**Comment by bhupiister** [comment]
@gkv311 I understand your concern. I even saw the video you shared, it was great watching it and especially someone accepting their mistake. Though the positive point was that they came back to unity :)
Since you are experienced person, I would like to know if there are any cross platform framework which I could choose instead of unity for mobile(IOS, Android) and WebGl ? like coding once and using all three planforms.

**Comment by gkv311** [comment]
@bhupiister, I don't think that there is a framework that makes a cross-platform development simple, nor that I can suggest something better without knowing details of your project. Open CASCADE Technology is also available on iOS, Android and Web (WebGL) platforms, but it is not a game engine and C++ is the main development language.

Starting with a framework that team already knows is usually a good choice, as long as there are no blocking issues with it. Every framework has it's strong and week points, bugs, unique features - experience with specific framework allows to achieve first results faster and to avoid / workaround known problems.

This is especially critical for a short project, where you don't have much time to learn technology and want to focus on project features. For longer and more complex projects this is not always the case - development of a custom engine doesn't look as a bad idea, when you develop something non-typical to questioned game engines.
